source :gemcutter

gem 'rails',                        '2.3.8'
gem 'json_pure',                    '1.4.6'
gem 'RedCloth',                     '4.2.3'
gem 'radiant',                      '0.9.1'
gem 'acts_as_list',                 '0.1.2'
gem 'sqlite3-ruby',                 '1.3.1',    :require => 'sqlite3'
gem 'haml',                         '3.0.17'
gem 'compass',                      '0.10.4'
gem 'compass-960-plugin',           '0.9.13'
gem 'rmagick',                      '2.13.1'
gem 'aws-s3',                       '0.6.2',    :require => 'aws/s3'
gem 'paperclip',                    '2.3.5',    :require => nil
gem 'radiant-go',                               :require => nil
gem 'radiant-forms-extension',      '>= 3.2.4', :require => nil
gem 'radiant-settings-extension',   '>= 1.1.1', :require => nil
gem 'radiant-images-extension',     '>= 0.4.0', :require => nil
gem 'radiant-layouts-extension',    '>= 1.0.1', :require => nil
gem 'radiant-drag-extension',       '>= 0.1.1', :require => nil